
name: import hosts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env: 
  AKAMAI_EDGEGRID_ACCESS_TOKEN: ${{ vars.AKAMAI_EDGEGRID_ACCESS_TOKEN }}
  AKAMAI_EDGEGRID_CLIENT_TOKEN: ${{ vars.AKAMAI_EDGEGRID_CLIENT_TOKEN }}
  AKAMAI_EDGEGRID_CLIENT_SECRET: ${{ vars.AKAMAI_EDGEGRID_CLIENT_SECRET }}
  AKAMAI_EDGEGRID_HOST: ${{ vars.AKAMAI_EDGEGRID_HOST }}
  AKAMAI_CONFIGID: ${{ vars.AKAMAI_CONFIGID }} 
  AKAMAI_CONFIG_VERSION: ${{ vars.AKAMAI_CONFIG_VERSION }} 

jobs:
  build:
    name: Update hosts
    runs-on: ubuntu-latest
    environment: globaldots
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run update
        run: go run -v .
