
name: import hosts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env: 
  AKAMAI_EDGEGRID_ACCESS_TOKEN: ${{ vars.AKAMAI_EDGEGRID_ACCESS_TOKEN }}
jobs:
  build:
    name: Update hosts
    runs-on: ubuntu-latest
    environment: globaldots
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run update
        run: go run -v .
