
name: Add hostnames to Akamai AppSec policy
on:
  workflow_dispatch:
env: 
  AKAMAI_EDGEGRID_ACCESS_TOKEN: ${{ vars.AKAMAI_EDGEGRID_ACCESS_TOKEN }}
  AKAMAI_EDGEGRID_CLIENT_TOKEN: ${{ vars.AKAMAI_EDGEGRID_CLIENT_TOKEN }}
  AKAMAI_EDGEGRID_CLIENT_SECRET: ${{ vars.AKAMAI_EDGEGRID_CLIENT_SECRET }}
  AKAMAI_EDGEGRID_HOST: ${{ vars.AKAMAI_EDGEGRID_HOST }}
 
jobs:
  build:
    name: Manage hostname list
    runs-on: ubuntu-latest
    environment: globaldots
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run update hostnames for AppSec
        run: go run -v .
